# Generated by Django 5.1.6 on 2025-02-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='tenant',
            new_name='tenancy',
        ),
    ]
