# Generated by Django 5.1.6 on 2025-02-25 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Tipo de Documento')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código de Verificação')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em: ')),
            ],
            options={
                'verbose_name': 'Tipo de Documento Fiscal',
                'verbose_name_plural': 'Tipos de Documentos Fiscais',
            },
        ),
        migrations.CreateModel(
            name='TaxDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=80, verbose_name='Número do Documento')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data do Documento')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Arquivo em Anexo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em: ')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Documentos', to='tax_document.documenttype', verbose_name='Tipo de Documentos')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenancy', verbose_name='Igreja')),
            ],
            options={
                'verbose_name': 'Documento Fiscal',
                'verbose_name_plural': 'Documentos Fiscais',
            },
        ),
    ]
