# Generated by Django 5.1.6 on 2025-02-26 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxdocument',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Documentos', to='tax_document.documenttype', verbose_name='Tipo de Documentos'),
        ),
    ]
