# Generated by Django 5.1.6 on 2025-02-26 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_document', '0002_alter_taxdocument_document_type'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='tenancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenancy', verbose_name='Igreja: '),
        ),
    ]
