# Generated by Django 5.1.6 on 2025-02-26 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_document', '0003_documenttype_tenancy'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='tenancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenancy', verbose_name='Igreja: '),
        ),
    ]
