# Generated by Django 5.1.6 on 2025-02-21 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        ('worker_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome: ')),
                ('bithday_date', models.DateTimeField(verbose_name='Data de Aniversário: ')),
                ('adress', models.CharField(max_length=255, verbose_name='Endereço: ')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de Telefone: ')),
                ('email', models.CharField(max_length=255, verbose_name='Email: ')),
                ('batism_date', models.DateTimeField(verbose_name='Data de Batismo: ')),
                ('is_worker', models.BooleanField(default=False, verbose_name='É obreiro? ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em: ')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenancy', verbose_name='Igreja: ')),
                ('worker_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worker_type.workertype', verbose_name='Classificação de Obreiro; ')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor da Contribuição: ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em: ')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenancy', verbose_name='Igreja: ')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member', verbose_name='Membro contrinuinte: ')),
            ],
            options={
                'verbose_name': 'Contribuição: ',
                'verbose_name_plural': 'Contribuições: ',
                'ordering': ['id'],
            },
        ),
    ]
