# Generated by Django 5.1.6 on 2025-02-25 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Entrada', 'Entry'), ('Saída', 'Exit'), ('Default', 'Default')], default='Default', max_length=15)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição: ')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor da Movimentação: ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em: ')),
                ('department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='department.department', verbose_name='Departamento relacionado a Transação: ')),
            ],
            options={
                'verbose_name': 'Transação Fiscal',
                'verbose_name_plural': 'Transações Fiscais',
            },
        ),
    ]
