# Generated by Django 5.1.6 on 2025-02-25 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiscal_transaction', '0001_initial'),
        ('tax_document', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscaltransaction',
            name='tax_document_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tax_document.taxdocument', verbose_name='Documento Fiscal Relacionado a Transação: '),
        ),
        migrations.AddField(
            model_name='fiscaltransaction',
            name='tenancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenancy', verbose_name='Igreja: '),
        ),
    ]
