# Generated by Django 5.1.6 on 2025-02-25 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('member', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada: ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição: ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em: ')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='department.department', verbose_name='Departamento: ')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member', verbose_name='Membro: ')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenancy', verbose_name='Igreja: ')),
            ],
            options={
                'verbose_name': 'Membro do Departamento',
                'verbose_name_plural': 'Membros do Departamento',
            },
        ),
    ]
