# Generated by Django 5.1.6 on 2025-02-21 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome: ')),
                ('description', models.TextField(verbose_name='Descrição: ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em: ')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenancy', verbose_name='Igreja: ')),
            ],
        ),
    ]
